n
{
    local i := 1;
    local k := 1;
    local tempk := 0;
    local j := 1;
    local flag := 1;

    while ((n <= 0) & ((flag <= 1) & (1 <= flag))) do {

        flag := 0;

    };

    while ((i <= n) & ((flag <= 1) & (1 <= flag))) do {

        while (j <= i) do {
            tempk := (tempk + k);
            j := (j + 1);
        };
        k := tempk;
        tempk := 0;
        j := 1;

        i := (i + 1);

    };

    k

}
